version: '3'

services:

  postgres-pix:
    container_name: postgres-pix
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: pix
    ports:
      - "15432:5432"
    networks:
      - pix-network

  pgadmin:
    container_name: pgdockeradmin
    image: dpage/pgadmin4
    restart: always
    ports:
      - "16543:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@admin.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    depends_on:
      - postgres-pix
    networks:
      - pix-network

networks:
  pix-network:
    driver: bridge